/* RCTools recovery profile: one minimal server for SSH and SFTP. */
#define DROPBEAR_SFTPSERVER 1
#define SFTPSERVER_PATH "/sbin/rctools-sftp-gate"
#define DROPBEAR_CLI_NETCAT 0
#define DROPBEAR_CLI_LOCALTCPFWD 0
#define DROPBEAR_CLI_REMOTETCPFWD 0
#define DROPBEAR_CLI_AGENTFWD 0
#define DROPBEAR_CLI_PROXYCMD 0
#define DROPBEAR_SVR_LOCALTCPFWD 0
#define DROPBEAR_SVR_REMOTETCPFWD 0
#define DROPBEAR_SVR_AGENTFWD 0
#define DROPBEAR_X11FWD 0
#define DROPBEAR_SVR_PASSWORD_AUTH 1
#define DROPBEAR_SVR_PUBKEY_AUTH 1
#define DROPBEAR_RSA 1
#define DROPBEAR_ECDSA 1
#define DROPBEAR_ED25519 1
#define DO_MOTD 0
